### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by qiaoqiaode1011** [siomkos2020/CEHMR#1]
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[9], line 18
     15 sys.path.append("..")
     17 from models.cehmr_net import CEHMRNet
---> 18 from utils import llprint, multi_label_metric, ddi_rate_score, get_n_params

ModuleNotFoundError: No module named 'utils'

**Comment by siomkos2020** [comment]
Sorry, it was my mistake that the utils.py file was not uploaded. We have uploaded all files.
